### ISSUE TITLE
like it, how to install k8s?

### ISSUE THREAD

**Issue by mvpbang** [girishg4t/k8sResourceCloner#1]

**Comment by girishg4t** [comment]
Hey @mvpbang,
Sorry for late reply now i have added the instruction in readme file, Please check and let me know if you need any thing more

**Comment by mvpbang** [comment]
thank you, i will todo it

**Comment by girishg4t** [comment]
Also i have create blog on this it is still in inital state but you can take the reference 
https://www.notion.so/5-min-guide-to-write-kubernetes-operator-using-Operator-SDK-4f9e4c393539476f8351937e36b0784e
